name: recommenda
description: A new Flutter project.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev
version: 1.0.0+1

environment:
  sdk: ">=2.16.1 <3.0.0"
   #sdk: ">=2.17.0-104.0.dev <3.0.0"
dependencies:
  cloud_firestore: ^3.1.8
  cupertino_icons: ^1.0.2
  firebase_auth: ^3.3.7
  firebase_core: ^1.12.0
  firebase_storage: ^10.2.7
  image_picker: ^0.8.4+9
  provider: ^6.0.2
  uuid: ^3.0.6
  intl: ^0.17.0
  flutter:
    sdk: flutter
  flutter_svg: ^1.0.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^1.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/logo.svg